feat:style: add updating status functionality and tidy comments
SpatialDays/stac-portal-frontend pull request #81
Opened 2023-08-10 13:36 UTC by mountaincharlie

2023-08-10 14:34 UTC, james-hinton commented on src/pages/CatalogManager/components/DownloadedCollections/index.jsx
> +      if (collection['stac-portal-metadata']['type-of-collection'] === 'public') {
Maybe in the future not all the collections will have the stac-portal-metadata key, so maybe we should check if it exists first

2023-08-10 14:34 UTC, james-hinton commented on stac-layer/src/index.js
> -console.log('James rocks')
oops

2023-08-15 09:27 UTC, james-hinton requested changes
could you format your code with this too please:
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2023-08-15 09:27 UTC, james-hinton commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/index.jsx
> +        let localFinishTime = new Date(item.time_finished).toLocaleTimeString()
we should always use const when the value wont be changed as it immutable variables saves memory

2023-08-15 09:27 UTC, james-hinton commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/index.jsx
> +    console.log('loadHistoryData', loadHistoryData)
can we get rid of console logs when merging to staging

2023-08-15 09:27 UTC, james-hinton commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/index.jsx
> +        let collectionStacUrl = item.newly_stored_collections
You should get the VSCode extension `prettier`, as in JS its convention we need semi colons after each line and prettier will do it automatically.

2023-08-15 09:27 UTC, james-hinton commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/index.jsx
> +  const [scrollX, setscrollX] = useState(0);
convention is `const [scrollX, setScrollX]`

2023-08-15 09:27 UTC, james-hinton commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/index.jsx
> +    return () => {};
this wouldnt do anything

2023-08-15 09:27 UTC, james-hinton commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/index.jsx
> +        <p>No load history to show</p>
how does this look? is it centered or have nice styling?

2023-08-15 09:27 UTC, james-hinton commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/style.scss
> +  &::-webkit-scrollbar {
/* Firefox */
& { scrollbar-width: none; }

/* IE/Edge */
&::-ms-clear {
    display: none;
}

2023-08-15 09:27 UTC, james-hinton commented on src/pages/CatalogManager/components/DownloadedCollections/components/SelectedCollectionModal/index.jsx
>        setEndDate(state.selectedCollection && state.selectedCollection.extent.temporal.interval[0][1] ? state.selectedCollection.extent.temporal.interval[0][1] : null);
this would crash the page if no temporal extent set (which can happen)

2023-08-15 09:54 UTC, mountaincharlie commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/index.jsx
> +        let localFinishTime = new Date(item.time_finished).toLocaleTimeString()
my bad, i thought because it was in a loop then the variables would be changing

2023-08-15 10:14 UTC, mountaincharlie commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/index.jsx
> +    return () => {};
that would be my inattention ...
same for the console.logs and useState naming convention

2023-08-15 10:14 UTC, mountaincharlie commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/index.jsx
> +        <p>No load history to show</p>
yh styled same as any other text on the modal

2023-08-15 10:16 UTC, mountaincharlie commented on src/pages/CatalogManager/components/DownloadedCollections/components/LoadHistoryTimeline/style.scss
> +  &::-webkit-scrollbar {
nice! i'll keep these in mind for future styling

2023-08-15 10:29 UTC, mountaincharlie commented
Cheers for the review!
All changes and recommendations made and ive applied correct formatting to all the files i can think of that ive worked on

2023-08-15 10:54 UTC, merged